// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test borrar limpiar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test borrar limpiar', async function() {
    await driver.get("http://127.0.0.1:5500/fundamentos/calculadora/calculadora.html")
    await driver.manage().window().setRect({ width: 974, height: 778 })
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(1) > .num")).click()
    await driver.findElement(By.css("tr:nth-child(4) > td:nth-child(2) > .num")).click()
    assert(await driver.findElement(By.id("resultado")).getText() == "45")
    await driver.findElement(By.id("borrar")).click()
    assert(await driver.findElement(By.id("resultado")).getText() == "4")
    await driver.findElement(By.id("limpiar")).click()
    assert(await driver.findElement(By.id("resultado")).getText() == "0")
  })
})
